#!/bin/bash

enable_xdebug=false

# set -e -- Exit immediately if a command exits with a non-zero status.
set -e

PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL"}

version="8.1"
types="apache2 cli"
# https://xdebug.org/docs/upgrade_guide
xdebug3_options="xdebug.mode xdebug.start_with_request xdebug.discover_client_host xdebug.client_host xdebug.client_port"

# Configure:
# - Error reporting
# - Max upload filesize
for type in $types; do
    path="/etc/php/$version/$type/php.ini"
    if [[ -f "/etc/php/$version/$type/php.ini" ]]; then
        sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' "$path"
        sed -ri "s/^error_reporting\s*=.*$//g" "$path"
        echo "error_reporting = $PHP_ERROR_REPORTING" >> "$path"
        echo "upload_max_filesize = 50M" >> "$path"
    fi
done

# Disable/enable loading xdebug extension
# We use this method because it gives the biggest performance increase, and because
# this will disable both apache2 and cli since their ini's are both symlinked to mods-available i.e.
# - /etc/php/8.1/apache2/conf.d/20-xdebug.ini
# - /etc/php/8.1/cli/conf.d/20-xdebug.ini
# Note: Disabling xdebug improves performance by 50%
path="/etc/php/$version/mods-available/xdebug.ini"
if [ -f "$path" ]; then
    value=";zend_extension=xdebug.so"
    if [ "$enable_xdebug" == true ]; then
        value="zend_extension=xdebug.so"
    fi
    echo "$value" > "$path"
fi
# Set xdebug options in php.ini files
for type in $types; do
    path="/etc/php/$version/$type/php.ini"
    if [ -f "$path" ]; then
        for option in $xdebug3_options; do
            value="On"
            if [[ "$option" == "xdebug.client_host" ]]; then
                value="172.17.0.1"
            fi
            if [[ "$option" == "xdebug.mode" ]]; then
                value="debug"
            fi
            if [[ "$option" == "xdebug.client_port" ]]; then
                value="9000"
            fi
            if grep -r "$option" "$path" > /dev/null; then
                sed -i "s/$option =.*/$option = $value/g" "$path"
            else
                echo "$option = $value" >> "$path"
            fi
        done
    fi
done

# Apache gets grumpy about PID files pre-existing, so remove them:
rm -f /var/run/apache2/apache2.pid

# Read default envvars, which includes APACHE_RUN_USER/GROUP=www-data
source /etc/apache2/envvars

# Start apache
# It seems like -DFOREGROUND is required for the container to work correctly
exec /usr/sbin/apache2 -DFOREGROUND
