name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=3s --health-retries=5
    env:
      SS_DATABASE_CLASS: MySQLDatabase
      SS_DATABASE_SERVER: 127.0.0.1
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: root
      SS_DATABASE_NAME: test
      SS_DEFAULT_ADMIN_USERNAME: admin
      SS_DEFAULT_ADMIN_PASSWORD: admin
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --prefer-dist --no-progress
      - run: vendor/bin/phpunit app/tests --fail-on-warning

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --prefer-dist --no-progress
      - run: vendor/bin/phpcs
